name: combined_provider
description: watch a list of providers and combine result
version: 0.0.1
author: Erlend Lind Madsen
homepage: https://github.com/erf/combined_provider

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: